name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - uses: actions/checkout@v3

      # Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Generate Prisma client
      - name: Generate Prisma Client
        run: npx prisma generate --no-engine

      # Apply DB Migrations
      - name: Apply DB Migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Sync agents metadata into the database
      - name: Sync agents to DB
        run: npm run sync:agents
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Run ESLint (JS/TS)
      - run: npm run lint

      # Run StyleLint (CSS)
      - run: npm run lint:style

      # Check Prettier formatting (will fail if unformatted)
      - run: npx prettier --check .

      # Build your Next.js app
      - run: npm run build
